apiVersion: v1
kind: Secret
metadata:
  name: agropacayales-secret
  namespace: agropacayales-k8s
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://axelhuapaya_db_user:lider2021@cluster0.oyk6ogs.mongodb.net/?appName=Cluster0"
  RDS_SQL_HOST: "agropacayales-rds.c123456789.us-east-1.rds.amazonaws.com"
  RDS_SQL_USER: "sa"
  RDS_SQL_PASSWORD: "ClaveSegura2026!"
