# kubectl apply -f ana-felix-05-deployment.yml
# kubectl delete -f ana-felix-05-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ana-felix-05-deployment
  namespace: ana-felix-05-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ana-felix-05-deployment        # Debe coincidir con las etiquetas del Service
  template:
    metadata:
      labels:
        app: ana-felix-05-deployment      # Debe coincidir con las etiquetas del Service
    spec:
      containers:
      - name: ana-felix-05-container
        image: hugo454/s5-springwebflux-mongodb:1.0
        imagePullPolicy: IfNotPresent          # IfNotPresent (usa imagen local) | Always (descarga de Docker Hub)
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: ana-felix-05-secret     # Carga todos los valores del Secret como variables de entorno
        #- configMapRef:
        #    name: ana-felix-05-configmap # Alternativa: cargar desde el ConfigMap en vez del Secret
