# kubectl apply -f ana-felix-05-secret.yml
# kubectl delete -f ana-felix-05-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: ana-felix-05-secret
  namespace: ana-felix-05-namespace
type: Opaque
data:
  MONGO_DATABASE: YWdyb3BhY2F5YWxlc19kYg==
  MONGO_URI: bW9uZ29kYitzcnY6Ly9hbmk6MjEyMTIxYW5hQGNsdXN0ZXIwLWFzaW1hcmtldC5oY200bnJ3Lm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIwLWFzaW1hcmtldA==
  SERVER_PORT: ODA4MQ==
  SPRING_PROFILES_ACTIVE: Y2xvdWQ=

# CONVERTIR A BASE64 CON PAGINA WEB:
# https://base64.guru/converter

# CONVERTIR A BASE64 CON POWERSHELL (Windows):
# [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("tu_valor_real"))
# [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String("tu_valor_base64"))

# CONVERTIR A BASE64 CON BASH (Linux/Mac/Git Bash):
# echo -n "tu_valor_real" | base64
# echo "valor_en_base64" | base64 --decode
